#+FILETAGS: introspection
#+DATE: <2013-09-30>
#+AUTHOR: Charanjit Singh
#+TITLE: Directionless Wandering


It has been about five years since I first got my computer. Endless
hours I have spent in front of the two dimensional rectangle, the third
world. Before I got the machine, most of my time was spent in the world
inside my head. My thoughts, feelings, sensations and so many things. I
was never at rest. Then I got the machine. I had dreamed of it for like
years before I got one. I was excited, fascinated. There were so many
things in my mind to do with the computer, so many plans of changing the
world. I couldn't harness any of them. Now it feels like every dream I
had back then has become a burden on my shoulders, depressing me, making
my feet heavy. Keeping me from moving forward. I am feeling powerless,
like I am losing a bit of life with every failed dream. I'm getting
frightened from dreaming. What have it brought to me other than burden?

Clarity of thoughts was never my strength, but nowadays I am feeling
much more puzzled. Lost. Like I am stuck. World is leaving me behind.
I've always seen the world like a witness. The third person standing on
the shore looking at the fishes racing, the canaries flying. Something
has happened. Making me feel as I am in the middle of the race I always
witnessed. Just witnessed. Never participated. Not even as audience. I
blame dreams. The fallen ones.

Yesterday on reddit I found a name for my madness. Existential
Depression they call it. It made me believe I am not the only one
feeling this. There are others. There might be others who have gone
through the path I am on now. May be they could give me a tip or two.
Here I am outside my diary, writing in public.

I have been into computers for so long. And yet I found myself no where.
So much time I have put into programming, operating systems, security,
psychology and so many other things. All seem wasted. It is depressing
to just look at all the mess I have made of me. I see people so less
talented than me, with no knowledge of what they are doing, even doing
it wrong, crossing me in terms of success. They are richer, happier, and
better than me. I know I can do what they are doing 10 times better, but
I don't. Instead of motivating me, it is drowning me even deeper. I feel
no motivation to finish any project I start. And when the unfinished
gets piled up, they haunt me. They make me angry and depressed. I can't
remember how many times I swiped my hard disk to get rid of the
unfinished 'awesome' projects I thought will change the world. So many
half written poems whose traces can't be found now in the burnt
notebooks. It sucks. I feel like every single thought I had, every new
idea I ever failed has cursed me. I have a trembling feeling just
thinking about thinking something new.

So many techniques I tried. So many psychology papers, books I read.
Still I am here. Another trough. I've tried the GTD (Getting Things
Done) and the concept of 'limited willpower'. Wrote all my mess down.
Tried to minimize the decision making. And so much more. This fucking
wave is just not leaving me. I find myself stuck in the crests and
troughs all the time. I am on the top of sky when on a crest. Have so
many new ideas, start new projects. Start reading new books. New
programming languages. New frameworks. New poets. And then it all start
fading. Then come the phase when I try to balance things. And just when
I feel I can do it, I find myself in middle of a trough. The disgust and
depression of it is just killing. I do many stupid things in troughs.
All failures. May be writing this blog post is one of them. May be after
some hours I will start feeling ashamed of writing such a thing, and
delete it. It just sucks to be here. I know it will pass. It always do.
But it leave behind scars. Scars that will keep scaring me from thinking
new ideas, from dreaming. And I think this might be the lesson. Dreams
suck.
