#+DATE: <2022-03-24>
#+AUTHOR: Charanjit Singh
#+TITLE: I have quit my job


Several years ago, I decided to quit freelancing and do a day job. The
job would pay much less but I was struggling with mental health (ADHD).
On my therapist's suggestion, I decided to give the job thing a try. It
worked wonderfully, my struggles with discipline are a thing of past. Or
so I believe.

Once again, I have decided to take a drastic step. I have decided to
quit my day job. This is my last week at work, coming Monday I will be
unemployed.

I don't have a plan. I haven't planned to leave work permanently. I
don't have an ambition either, world changing or otherwise. This post is
me deciding to take a break from work and finding reasons for doing so,
after the fact.

** Curiosity
   :PROPERTIES:
   :CUSTOM_ID: curiosity
   :END:
It is exciting. The possibilities are endless. It is scary. Endless
possibilities means a lot of them lead to failure. Odds are stacked in
my favor in some regards; I am good at what I do, world will still need
good software engineers 6 months down the road. They are not so much in
my favor in some regards; precedence says I will fall into inaction and
misery, and achieve nothing. Complete nothing. I've almost always lost
in my struggles with ADHD in past. There is a good chance that I am
deluding myself into believing that this time will be any different.

I am curios of whether it is me who has finally tamed the beast, or if I
am going to need the structure a formal job as crutches.

** Exhaustion
   :PROPERTIES:
   :CUSTOM_ID: exhaustion
   :END:
I am sort of exhausted from making pragmatic decisions all the time.
Building software needs a delicate balance between what makes your
software technically good, and what makes it actually good. Actually
good software solve problems despite its own imperfections.

I want to spend some time making impractical decisions. I want to build
software which solve the problem of making me happy, or at least
entertained.

** Heartbreak
   :PROPERTIES:
   :CUSTOM_ID: heartbreak
   :END:
I joined my last company because I was sold on an idea. An idea of a
project which was solving a meaningful problem, and was challenging
enough to keep me engaged. I dedicated myself to that, gladly making
many sacrifices in my personal life. I got to build a team and lead it
with autonomy, we built a stolid product (actually, a part of it). And
then I was taken off that project, with what felt like without warning.
I accepted that decision because it was practical for the company.

But I was unprepared for the aftershock. It was traumatizing. With a
snap I was plucked out of one project, and added into another with the
expectation of establishing myself into a similar critical role. The
fact that I did it without a break didn't help. I could no longer find
that sense of belonging anymore, in this new project, or others that
came after.

Perhaps I am not suited for working in a services company with rapid
transitions. Perhaps I set my expectations wrong. Perhaps there was a
lapse in communication. Perhaps, I need to spend some time grieving.
Regardless, I need a break.

** Self growth
   :PROPERTIES:
   :CUSTOM_ID: self-growth
   :END:
As good a workplace as Trantor has been, I've been feeling stagnated for
a while. I have learned a lot outside of work, but work has started to
feel like work, which makes me miserable. Overlap between things I want
to learn and things which my job needs have been steadily and
increasingly decreasing.

Many of the things I want to learn need dedication which I can't afford
while working full-time as a software engineer. There is no off-switch,
I am always working; even when I am not sitting in front of a computer.
Things I want to learn need me 100% there.

** Social work
   :PROPERTIES:
   :CUSTOM_ID: social-work
   :END:
This is the most delusional of all the reasons I've cooked up. I imagine
building solutions to problems I see in my surroundings. For some
irrational reason, I feel a desire to give back to society. This is
perhaps narcissism finding its way around my reasoning, coloring itself
righteous. More logical would be to uproot myself and immigrate to a
place where people have already solved the basic problems of human
coexistence.

When I was in school I used to imagine how the school can be reformed,
in college it was the education system, as a freelance developer I
actually started acting on my imaginations and trying to improve my
local tech community. Several times. As an employee, I tried to uplift
my team (and imagined work reform, but never acted on it). Now, I
imagine solutions for many of the problems I see my village face. I am
curious if I will put them into action.

* What lies ahead?
  :PROPERTIES:
  :CUSTOM_ID: what-lies-ahead
  :END:
I don't know. There are too many things. There is a very good chance
that I am going to freeze in the face of choice, be miserable for a few
weeks, and get back to doing a day job. I am going to take time off for
as long as I feel like it, or run out of money. During this time I will
try to learn things and build software that bring me joy. Try to teach
myself how to focus more on the journey.

I've observed that many activities (including building software) can be
a meditative experience. If you can let go of the goals, you can quite
enjoy the act. Counter intuitively, the result is often much better. But
it is not always on time, which makes this a dangerous thing to do when
someone else is paying for my work. Perhaps the last bit is because I am
not yet well versed in it. This too might be a matter of finding a
balance. I'll explore.
