#+FILETAGS: introspection
#+DATE: <2016-08-23>
#+AUTHOR: Charanjit Singh
#+TITLE: Losing to Nothingness


Couple weeks back I executed my plan to return to Chandigarh. The plan
was to take a break from work and relax for a bit, teach myself some new
skills. The real life butted in and I haven't started the phase 2 yet,
but the change was big and I am feeling the affects.

I strive to build bubbles of order in midst of chaos that is life, but
what's still a mystery to me is why change give me a high. Bigger the
change higher the crest. In my final days in Bangalore I was almost at
the deepest of the limbo; shifting almost brought me back on track. The
crest is usually temporary, I am certain same is the case this time as
well. Usually I meet equally deep troughs. Just thinking of it give me
the chills.

However, something is different this time. I am ought to be on a high,
yet I am feeling the pull of a trough. It feels even weirder than it
sounds. I feel very peaceful, yet there is this unanswerable
restlessness. I feel an insatiable hunger at all times, as if there is a
big void in middle my stomach which is pulling my abdomen inside. The
peace is such I could die right now and not have a single regret, not a
thing I want to do more or different. Same time there is this alarm that
just keep ringing for all the things I have left undone. All the
promises to be fulfilled.

Duality yet has some constants, some patterns are emerging. I am living
on 6th floor these days. It provide quite a demi-god view of the
neighborhood; looking at automated people, day in and day out. It raise
so many questions; so much of my own life is just acting on impulses. An
unclear realization is rendering so much of life to nothingness. It's
like I've reached a conclusion, I don't know to what. I don't know what
it is. A cluster of thoughts I can't tell apart. Perhaps this is how it
feel like when entering the actual madness.

What I fear most is that I might be concluding life. It is becoming
harder and harder to convince myself to live for gathering things. I've
always had a loose grip on reality, now I am fighting to hang on to
however little I have left. Paranoia and delusions are coming back.

It feels like a storm is approaching, yet it's so calm. I am dreadfully
afraid, but something in me is welcoming it. May be this is the eye of
the storm I am in. It sure feel like somewhere there's a clock, ticking.
There is so much going on in my silly little head, and there is this
emptiness sucking me in.

I fear I might be losing to this nothingness. I am scared the peace is
temporary, but the chaos is just getting started.
