#+DATE: <2015-04-13>
#+AUTHOR: Charanjit Singh
#+TITLE: Please Don’t Fuck Up the Hackathons


I came to Bangalore few months back attracted by its humming tech
culture, lots of meetups and even more so, hackathons. I work as a
freelancer, I have no other purpose here. And I was not disappointed
until recently. Honestly, I don't even know what definition of word
"hackathon" has for Bangalore. I'd quote Paul Graham here, "the city
sends you a message". Bangalore certainly doesn't give a message of
freedom or even innovation, the message I heard when I came here was
that of "milk whatever you can". People running after money. End of
story. But it still has a (relatively) pretty healthy tech-culture.

I believe hackathons are meant for open innovation. An event where
people go and build something, anything that come to their mind. I don't
mind themes. But giving me a "problem statement" to work on is
ridiculous. It is no more a hackathon when you want everyone to climb
the same tree to "win". I don't go to hackathons for "winning" them. I
don't know what kind of geek does that. Hackathons are for hackers, for
having fun, for our happiness, for teasing the brain muscles which we
can't utilise in our day jobs. The word "hack" in hackathon means
innovation. Anything useful that comes out of a hackathon is a
by-product, never the primary goal. It's sort of paradoxical.

Beauty of a hackathon is that there is no stressful competition. There
is nothing to compare against, which lead to a very healthy kind of
competition (which might not even be called competition). I'd suggest to
read this if you'd like to better understand the
[[https://web.archive.org/web/20151124075842/https://medium.com/@pedramkeyani/hacking-company-culture-1daa3be1d769][spirit
of a hackathon]].

The one major piece of crap that I think is on the way to ruin
hackathons in Bangalore (at least) is this company called
[[https://web.archive.org/web/20151124075842/http://www.venturesity.com/][Venturesity]].
Their main idea is to organize hackathons for companies so they can hire
the winners (or whomever, may be). But the way they organize the event
is what bothers me. They give 2-3 problem statements and ask people to
solve them. Recently they've also made it compulsory to have a
[[https://web.archive.org/web/20151124075842/http://en.wikipedia.org/wiki/Software%5Fdesign%5Fdocument]["design
document"]] for the problem statement they send one day before the
event.

If some company actually want to hire some good hackers, then this
(venturesity) monkey-business is definitely not what they should be
doing. You kill the spirit of the hackathon, reduce it to a mere race
where everyone is climbing the same tree, and then you judge them to
"hire" them? Is this the best Bangalore's hackers could come up with?
There are so many things you could innovate, and you chose the same
retarded system of master race that's ruining education in our country.
I don't personally know the people behind venturesity, but I can bet
there is some academic from some big-shot school pulling the strings.

Interviews are not perfect, may be not even good, I agree with you
there. But this ventursity hackathon hiring shit is a step backward. It
is a night long exam which is anything but fun. When I look at this
situation, I don't see Venturesity solving a problem, they are milking
an opportunity which is not theirs to milk (you are not fucking hackers,
stay away from hackathons). They are in fact creating a problem of their
own. Soon people will follow the suit and in worst case Indian
hackathons will all be this bullshit Venturesity does. World is full of
monkeys you see. We all know how everything gets an Indian version, and
I don't want this to be Indian version of hackathons.

In the end, if there's someone from ventursity reading this or if
someone can take this message to them, I'd like to personally say
something. My problem is not with companies using this strategy for
hiring, or with Venturesity doing business. My problem is with you
calling it a hackathon. Please stop calling your events hackathons.
Because they are fucking not. Call them hire-e-thons or
night-long-exams-because-we-couldnt-innovate or whatever, but please
don't call them hackathons. It gives a very wrong message to the
community about what a hackathon is.

*YOU ARE FUCKING RUINING HACKATHONS FOR EVERYONE.*

Once again with due respect, please don't ruin one good thing in
Bangalore I love, it's tech culture.

** UPDATE 1
   :PROPERTIES:
   :CUSTOM_ID: update-1
   :END:
So I got a response from Venturesity after a friend posted this post in
their private group. This is what they said and my reply:

Venturesity: The problem statements are well-defined practical problems
which our clients are trying to solve themselves. Though they may seem
rigid at times, they leave enough room for creativity and innovation.
Our asking for a design document ensures serious participation.

There will be stress when anyone tries to program/debug anywhere. But we
try to make the event as less stressful as possible. There is always
good food/music/dance to take the edge off.

We appreciate the criticism, Charanjit :)

Me: Putting a theme on a hackathon is the restriction which encourages
innovation, giving a "problem statement" is not. I don't think it
matters how well defined the problem statement is, you simply change the
meaning of the word hackathon when you push a problem statement for
everyone.

What do companies want to achieve with the venturesity hackathons? Good
hackers as employees. Is racing the only way to do that? Say Stayzilla
want employees who can work in hotels domain. They gave us problem
statements and looked for people who demonstrated the qualities required
to solve those specific problems, and who can race. If they had chosen
to just theme that hackathon saying “theme is stay in hotels (or
something more creative), and we'll judge projects by 1. data mining
fu 2. Our API fu 3. Whatever their third problem statement was

Companies are putting a lot of money in there, they should be clear
about what they want and try not to damage the culture. If they want to
hire "hackers" with vision and creativity along with the ability to
code, they should innovate and change their approach here a bit.

If all the companies want are code-monkeys who race all day to achieve
goals in cubicles, then that is fine too. Just don't call it a
hackathon. Because it is not. When you give a too restrictive (or even
open) "problem statement" you killed the hack of hackathon, it's just a
(mar)athon that is left behind.

I respect companies for putting the money and for showing openness for
hiring. May be they are expecting to see innovative solutions to some of
their problem statement (like you said) that they can use from the
hackathon. But won't it be better if they let people truly innovate in
aspects the company has not thought of yet? They might get something
they haven't even imagined/envisioned yet, and they will surely get the
most innovative minds which they can then use for solving the problem
statements they actually need solved.

I don't want to be too mean, but I didn't really expect Venturesity to
see the problem here. If they could, they would've seen it by now.

Also design documents is not a solution to their problem of "serious
participation". Have you never participated in some big hack before?
Just copy ‘em if you can't participate. Why don't you ask people to
submit ideas, and have their github/linkedin/resumes (you already
collect that info) and filter ‘em by hand. Design Document thing is more
bad than problem statements.

PS Stress in a hackathon is a luxury. We love it. That is the prime
motivator in a hackathon for pushing to the limit.
