#+DATE: <2015-09-12>
#+AUTHOR: Charanjit Singh
#+TITLE: Reality


It is one of those rare times I decide to write a blog post without life
taking a huge shit on me. Or am I just projecting success for attracting
success? Guess bitches. Hope you're all living in reality and not losing
yourself in your imaginary fantasy world. Guess what? You're not living
in reality. There is no reality to live in.

Reality like God can not be seen, observed, or proven. Even those
fucking scientists giving hardcore "laws" of physics say there can be
other realities where our laws of physics don't apply. Hell they don't
apply everywhere in our own dimension (hint: Quantum of Solace was a
douchie movie ).

Even if there is a *reality* (emphasis not mine, don't know who did it)
to observe and live in, human mind (and eyes) are certainly out of their
league to observe it for what it is. Fuck we can't even understand what
the person in front of us is saying, we only understand what we hear.

** Personal Realities
   :PROPERTIES:
   :CUSTOM_ID: personal-realities
   :END:
We all live in our own versions of personal realities, sort of like
bubbles all our lives and thoughts and even imaginations are trapped in.
Reality is that we can't know the reality. We'll always live in one
bubble or other. Best you can do is choose your bubble, and switch from
time to time. More bubbles you observe, better your chances are to not
get locked in one.

Everyone is living in a bubble. Some are aware of it, most are not.
People see through lenses they wear over time. With time the lenses get
different shades, get thicker and thicker. At the end of it, your whole
life is a fucking opinion.

People in fact, live in more than one bubbles. Bubble of "ethics" given
by your parents, religion and society, the "professional" bubble most
get caught in when they taste the thing they think is success for first
time (this one is easiest to detect, look around, ask people why they're
doing what they're doing), the "love" bubble you get trapped in from
movies and fairy tales, and many more.

** Probabilities
   :PROPERTIES:
   :CUSTOM_ID: probabilities
   :END:
You have no control over your life. Life is not yours to control, it is
not real. Everyone around you is carrying their own reality, overlapping
and interfering with yours. Best chance you've got is a chance. If you
want to make something happen, you can only increase its probability of
happening. Doesn't mean you should lose hope and go home (if you thought
that, you probably should give up and go home), if you wanna make
something happen, you gotta keep increasing the probability of its
occurrence until the probability is 1. Or spend your 80 years of misery
trying to do so.

** People
   :PROPERTIES:
   :CUSTOM_ID: people
   :END:
When I see people around, I try to think of them as different realities.
Every single one of them is living in their own reality. You'd be
surprised to find out how easy it is to manipulate someone (read bend
people to your will) once you can empathise with their reality.

The only way to observe a (wo)man's reality is to observe it from the
outside. Like I said, it is not the reality, it is a bubble. Most people
are hardcoded in their bubbles. Bubbles are like games (or is it my
bubble kicking in?), bubbles have rules too. Like every game has its own
rules of physics, bubbles have their own rules. Even if you can't live
another person's bubble, you can read their rules. If you can do it well
enough, you can tell exactly what other person is thinking and what he's
going to do in next 5 minutes, or 5 years.

You know the couples which live together (happily) can communicate
without talking, can tell what's up in other person's mind. My theory is
that by being close for long enough time, their bubbles start
overlapping. Like Van diagrams, there is that area in which they think
exactly same things. They don't need words anymore to communicate,
because they know what other person is feeling (and hence thinking,
wanting to say or do or whatever, old people creep me out).

** Reading the bubbles
   :PROPERTIES:
   :CUSTOM_ID: reading-the-bubbles
   :END:
It's not confined to couples, neither you need to live with someone for
a lifetime to be able to observe their bubbles. It is a skill, an art
perhaps. Some people are damn good at it.

It is easy to observe others' bubbles. The basic and most difficult
requirement is already met. You are already outside the bubble, now all
you have to do is study it from inside without entering it. Easy, huh?
Look for the reflections. Make them talk, don't listen to what they say,
look for the patterns. Patterns tell you the rules of their worlds. Try
to imagine how it is to see through those eyes. That is a whole
different world that person is seeing, it is, fascinating to say the
least. (Fuck I just told you my mind reading trick, I think I should
stop blogging)

You need the right set of tools to think in. Like in software it's all
about the right abstractions. This whole "bubbles" thing is just that, a
tool to think in. Ultimate goal is to be able to look at the world
exactly as someone else, find out the patterns, and hence the rules. And
of course ultimately play the rules for fun and profit.

Or you can take the script-kiddie way and jump to finding rules,
skipping the hardest first part. But that route involves lot of trial
and error, failure may result in bitter relations for life. Plus, you
lose all the scope for creativity and flexibility when you take the
latter way.

** Business
   :PROPERTIES:
   :CUSTOM_ID: business
   :END:
These "personal realities" can (and are) actually be used for
manipulating people to do what you want.

People live in many bubbles; many people live in similar bubbles.
Bubbles have rules, similar bubbles have similar rules. The textbook
tricks salespeople do lie in that domain. The whole range of tricks an
Indian sales person use everyday, won't work if he move shop to US. The
whole mutual reality his customers live in just changed. (There are of
course certain universal rules which work with almost all humans. How
many years of evolution was it again?)

That's rudimentary though. *Personal realities* can actually be created.
You are a sales guy, imagine if you could create a world where people
think they need your towels although they don't ever bath or wash their
hands (nasty people, I like 'em already). You can do that for one person
at a time, or N people at a time where N is the number of people who
watch the news you control, or (be less dramatic) people who watch your
advertisements. Again there are different levels of sophistication with
which this can be done. More you know about someone (that's why you make
'em talk), their habits etc, easier it is to manipulate and fabricate
entirely new realities for them. Imagine how fun the life would be if
you were Facebook or Google. I've heard Facebook knows even when and how
many times you go to poop everyday.

You didn't think I was all evil trying to teach you how to manipulate
people as I do, did you? Well that's certainly a perk, but the goal is
to be able to identify the realities from induced realities, and
fabricated realities (there's a difference). See I was trying to save
you all this time, you silly! I am no evil! Come on now jump in my van
already, I have tinfoil hats too.

I'll probably talk about this in depth later some time, about the
different tools I've figured people using, some unused ones I've
discovered through experimentation, and other delusional shit.

I could write a book about it, but I gotta go watch that movie everyone
on Reddit has started talking about all of a sudden.
