#+FILETAGS: introspection test lol
#+DATE: <2018-11-10>
#+AUTHOR: Charanjit Singh
#+TITLE: Relationships


Romantic relationships are such amazing things. I have had moments in my
life when I considered myself to have a certain level of control on my
mind; in terms of that I can witness myself as an outsider. The
introspection, the self awareness that make me think that, very rarely
accompany me when I am in a relationship. It seem to have a liking to
solitude.

Looking at it from far really brings the picture of a "family man" home.
A lone man seem to have the ability to accomplish much more than a man
bound to another person. It takes a lot of energy just to be with
someone. It has been 220 days since I last wrote a diary entry; my
primary medium of introspection. I've been so lost in the everyday
churn, I chose not to give time to my self. Not that I am complaining;
I've been happily lost.

For however many gifts solitude brings, the pain of loneliness is not
something to fool around with. Perhaps it is the pain itself that make
great people do great things, but it did make me realize the meaning of
crippling in crippling depression. Perhaps this is one of the reasons
successful people credit half their success to their partners. It must
be possible to have partners that can assist each other unlock their
potentials. Can you be so alone with someone? I wonder if it is a matter
of finding someone right, or making yourself right for the one you are
with. I am going to put all my eggs in the latter basket. We'll see how
this gamble plays out.
