#+FILETAGS: introspection
#+DATE: <2018-09-11>
#+AUTHOR: Charanjit Singh
#+TITLE: That sounds fun!


I got an opportunity to introspect in a conversation with a client when
he questioned my use of the word "fun". What do I mean when I say
something is fun? I am not entirely sure. May be when I see something
that excites me a little. People have very different interpretations of
fun. For me it is usually applying creativity to build something.
Activities the involve combination of these two, make me feel most
satisfied. Balance is very important.

But what do I really mean when I say something is fun? I almost never
know if it is going to be fulfilling at the time of making this
declaration. So how do I reach the point where I can say that X is going
to be fun?

It might be is the opportunity to learn something new. The unknown
scares me. It's a thrill and possibly vain feeling of growth. I have a
long list of things I want to learn/master. When my mind sees an
opportunity to check a box off of that list it gets excited.

It might as well be pure vanity. Vanity plays important part in my mind.
When my subconscious thinks keeping appearances is important, seeing a
geeky-sounding statement just automatically make it blabber "that sounds
fun". Although I try to keep my narcissism in check, occasional slips
are a thing.

Another thing that I think I consider fun is "fixing" something. It is
quite possible to mark me as a control freak; although I won't
voluntarily accept in a normal setting. I do however occasionally attain
rather strong opinions about how certain things shall be. When I see an
opportunity to "fix" something to my definition of right, that is a
strong motivational force. However unreliable it might be, working with
motivation is fun.
