#+DATE: <2018-02-27>
#+TITLE: About


I write software to make a living. I enjoy doing so. Both writing
software and making a living.

I also enjoy writing, giving talks and discussing engaging topics.
Mostly technical. This website has things I am willing to share
publicly. You can go through my blog [[/blog][posts]],
[[/categories/poem][poems]],
[[http://github.com/bitspook/][projects]],
[[https://slides.com/bitspook][talks]], or if you are considering
hiring a software architect, then
[[https://docs.google.com/document/d/1HFOxl97RGtuhAX95AhGWwa808SO9qSCYLjP1Pm39la0/edit][my
resume]] as well.

I believe writing software is a lot more than just churning out code.
Software is incarnation of programmer's thoughts. Software is a way of
life. The better one know oneself, clearer (s)he can think, better (s)he
can code. I see getting better at life as a way of getting better at
writing good software; and vice-versa.

I enjoy learning new things, and have dabbled around multiple dimensions
of technology; e.g web/software development, penetration testing,
reverse engineering and IOT.

My life more or less revolves around computers and related stuff. I
enjoy thinking and thought exercises; writing software is one of my
favorites.

I am open to take freelancing work. I have most experience in
Javascript/Typescript (both frontend and backend); but can also
comfortably work with Python, Golang, Haskell and Purescript.

This blog is an open journal in a way. Usually, I write here when I want
to - give my thoughts more structure than my personal journal approves -
share my thoughts with the world, as an act of shouting in the void -
use the act of making my thoughts public to attain solidifying
