#+FILETAGS: security trantor
#+DATE: <2020-08-06>
#+TITLE: Microservices


I recently joined a Whatsapp group named "Tech Blend", which conduct
weekly online meetups. Topic for last meetup was "Microservices", for
which I volunteered. Since I was working for around 2 years on a
microservices based project of decent complexity, I thought it would be
fun to talk about my experience.

The meetup was fun. I ran out of time. The meetup is quite well managed.
Manpreet, the guy who organizes the meetup does a very good job
respecting everyone's time while managing to have meaningful discussions
at the same time. Their topics/talks are usually quite shallow, but this
event management is something I can learn from participating in this
group.

Here are the slides for I created for the meetup. I was holding on to
them hoping I'll create a video, but that's not happening. So I am just
putting the slides over here.

Feel free to hit me up if you need some help regarding microservices, or
if you need me to explain some slide, or just for a chat.

#+begin_export html
  <iframe src="//slides.com/bitspook/microservices/embed?style=light" width="100%" height="420" scrolling="no" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen>
  </iframe>
#+end_export
