`(div
  ((id . "mc_embed_signup"))
  (form ((action . "https://bitspook.us14.list-manage.com/subscribe/post?u=de25614414d7e23ac4c3ea700&id=b8b47d5b6e")
         (method . "post")
         (id . "mc-embedded-subscribe-form")
         (name . "mc-embedded-subscribe-form")
         (class . "validate")
         (target . "_blank"))
        (div ((id . "mc_embed_signup_scroll"))
             (h2 nil "Get updates via email")
             (div ((class . "mc-field-group"))
                  (input ((type . "email") (value . "")
                          (placeholder . "Email Address") (name . "EMAIL") (class . "required email
newsletter-email") (id . "mce-EMAIL"))))
             (div ((style . "position: absolute; left: -5000px;")
                   (aria-hidden . "true"))
                  (input ((type . "text")
                          (name . "b_de25614414d7e23ac4c3ea700_b8b47d5b6e")
                          (tabindex . "-1")
                          (value . ""))))
             (div ((id . "mce-responses")
                   (class . "clear foot"))
                  (div ((class . "response")
                        (id . "mce-error-response")
                        (style . "display: none")))
                  (div ((class . "response")
                        (id . "mce-success-response")
                        (style . "display: none"))))
             (div ((class . "optionalParent"))
                  (div ((class . "clear foot"))
                       (input ((type . "submit")
                               (value . "Subscribe")
                               (name . "subscribe")
                               (id . "mc-embedded-subscribe")
                               (class . "btn btn-primary"))))))))
