`(ul ((class . "generic-listing"))
     ,@(seq-map
        (lambda (post)
          `(li ((class . "generic-li"))
               (span ((class . ,(concat "li-icon li-icon--" (alist-get 'category post)))))
               (div ((class . "generic-li-conent"))
                    (a ((href . ,(alist-get 'url post))
                        (class . "generic-li-title"))
                       ,(alist-get 'title post))
                    (span ((class . "generic-li-meta"))
                          (span ((class . "meta-item date"))
                                ,(format-time-string "%B %d, %Y" (alist-get 'date post)))
                          (span ((class . "meta-item tags"))
                                ,@(seq-map
                                   (lambda (tag)
                                     `(a ((href . ,(concat "/tags/" tag)))
                                         ,(capitalize tag)))
                                   (alist-get 'tags post)))))))
        posts))
